# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GeoLocus' do

pod 'Alamofire', '~> 3.0'
pod 'SwiftCharts', '~> 0.3'
pod 'SDWebImage', '~>3.7'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Zip', '~> 0.2'

end

target 'GeoLocusTests' do

end

